# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_table <- function(x, y, w) {
    .Call('_bento_cpp_table', PACKAGE = 'bento', x, y, w)
}

